name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 \
            libgraphene-1.0-0 \
            libwoff2-1.0 \
            libvpx9 \
            libevent-2.1-7 \
            libopus0 \
            libgstreamer1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libflite1 \
            libavif16 \
            libharfbuzz-icu0 \
            libsecret-1-0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libgles2 \
            libx264-dev
      
      - name: Install Playwright
        run: npm exec playwright install --with-deps
      
      - name: Lint
        run: npm run lint

      - name: Deploy for testing
        run: |
          npx serve@latest out &
          echo "Serving app in background"
          # Wait for the server to be ready
          timeout 30s bash -c 'while ! curl -s http://localhost:3000 > /dev/null; do sleep 1; done' || exit 1
          echo "Server is ready"

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up background processes"
          pkill -f "serve" || true