name: Staging Deployment

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      
      - name: Deploy for testing
        run: |
          npx serve@latest out &
          echo "Serving app in background"
          # Wait for the server to be ready
          timeout 30s bash -c 'while ! curl -s http://localhost:3000 > /dev/null; do sleep 1; done' || exit 1
          echo "Server is ready"

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run E2E tests
        run: npm run test:e2e
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up background processes"
          pkill -f "serve" || true